---

- name: Create new nat gateway and allocate new EIP if a nat gateway does not yet exist in the subnet.
  ec2_vpc_nat_gateway:
    state: present
    subnet_id: "{{ public_subnet_id }}"
    wait: yes
    region: "{{ aws_region }}"
    if_exist_do_not_create: true
  register: nat_gateway


- name: Set NAT Gateway ID in variable
  set_fact:
    nat_id: "{{ nat_gateway.nat_gateway_id }}"
